apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grade-management-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grade-management
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  
