apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s-deploy/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5696"
      port: 5696
      targetPort: 5696
    - name: "15696"
      port: 15696
      targetPort: 15696
  selector:
    io.kompose.service: rabbitmq
