apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s-deploy/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s-deploy/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://mongo:27017/grade_management
          image: fabianlusm/gm-web:0.1.1
          name: gm-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
