services:
  web:
    build: ../
    environment:
      - DATABASE_URL=mongodb://mongo:27017/grade_management
    volumes:
      - .:/tests
    links:
      - mongo
    logging:
      driver: none
  mongo:
    image: mongo:latest
    volumes:
      - grades_mongo_test_container:/data/db
    logging:
      driver: none

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - web
      - mongo
    volumes:
      - .:/tests
    environment:
      - DATABASE_URL=mongodb://mongo:27017/grade_management

volumes:
  grades_mongo_test_container:

networks:
  default:
    name: grades_test
    external: True
